[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "v0.150.0" # 👈 IMPORTANT: Replace with your version from Step 1
HUGO_ENABLE_GIT_INFO = "true"




# This rule makes the app show up on your domain
[[redirects]]
  from = "/apps/*"
  to = "https://cpg-ai-solutions.streamlit.app/:splat" # Replace with your Streamlit URL if different
  status = 200
  force = true # This makes the rule more powerful